/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutTemplatesRouteImport } from './routes/_layout.templates'
import { Route as LayoutShowcaseRouteImport } from './routes/_layout.showcase'
import { Route as LayoutHistoryRouteImport } from './routes/_layout.history'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTemplatesRoute = LayoutTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShowcaseRoute = LayoutShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoryRoute = LayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/editor': typeof EditorRoute
  '/history': typeof LayoutHistoryRoute
  '/showcase': typeof LayoutShowcaseRoute
  '/templates': typeof LayoutTemplatesRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/editor': typeof EditorRoute
  '/history': typeof LayoutHistoryRoute
  '/showcase': typeof LayoutShowcaseRoute
  '/templates': typeof LayoutTemplatesRoute
  '/': typeof LayoutIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/editor': typeof EditorRoute
  '/_layout/history': typeof LayoutHistoryRoute
  '/_layout/showcase': typeof LayoutShowcaseRoute
  '/_layout/templates': typeof LayoutTemplatesRoute
  '/_layout/': typeof LayoutIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/history'
    | '/showcase'
    | '/templates'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/editor' | '/history' | '/showcase' | '/templates' | '/' | '/api/trpc/$'
  id:
    | '__root__'
    | '/_layout'
    | '/editor'
    | '/_layout/history'
    | '/_layout/showcase'
    | '/_layout/templates'
    | '/_layout/'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  EditorRoute: typeof EditorRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/templates': {
      id: '/_layout/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof LayoutTemplatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/showcase': {
      id: '/_layout/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof LayoutShowcaseRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/history': {
      id: '/_layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutHistoryRoute: typeof LayoutHistoryRoute
  LayoutShowcaseRoute: typeof LayoutShowcaseRoute
  LayoutTemplatesRoute: typeof LayoutTemplatesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutHistoryRoute: LayoutHistoryRoute,
  LayoutShowcaseRoute: LayoutShowcaseRoute,
  LayoutTemplatesRoute: LayoutTemplatesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  EditorRoute: EditorRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
